@echo off
setlocal EnableExtensions
set "ASAP_RECIPE_OPEN_BROWSER=1"
set "ASAP_RECIPE_BROWSER_HOLD_SECONDS=1"
set "ASAP_RECIPE_BROWSER_FINAL_HOLD_SECONDS=10"
call "%~dp0RUN_ASAP_FULL_RECIPE.cmd"
exit /b %ERRORLEVEL%
